import subprocess

def run_shell(command):
    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True
        )
        out = (result.stdout or "").strip()
        err = (result.stderr or "").strip()
        if out:
            return out
        if err:
            return err
        return "(no output)"
    except Exception as e:
        return f"ERROR: {e}"

def write_file(path, content):
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return f"File written: {path}"
    except Exception as e:
        return f"ERROR: {e}"

def read_file(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return f"ERROR: {e}"

def patch_file(path, instruction):
    return f"[PATCH REQUEST]\\nFile: {path}\\nInstruction: {instruction}"

# ── KRAKEN TRADING MODULE ───────────────────────────────────────────────
# Auto-generated by handoff script. 
# Provides KORA with the ability to call: kraken_trade("buy", "XBTUSD", 0.5, 60000)
# ─────────────────────────────────────────────────────────────────────────
import subprocess
import os

def kraken_trade(action: str, pair: str, amount: float, price: float = None):
    """
    Executes a trade via the Kraken CLI.
    
    Parameters:
    - action: "buy" or "sell"
    - pair: e.g., "XBTUSD" (Bitcoin) or "ETHUSD"
    - amount: Quantity to trade
    - price: Limit price (optional. If not provided, executes market order)
    """
    # Ensure Kraken CLI is installed
    if not os.path.exists("/usr/local/bin/kraken"):
        print("[KORA] Installing Kraken CLI...")
        try:
            subprocess.run(
                ["curl", "--proto", "=https", "--tlsv1.2", "-LsSf", 
                 "https://github.com/krakenfx/kraken-cli/releases/latest/download/kraken-cli-installer.sh", 
                 "|", "sh"], shell=True, check=True, timeout=120
            )
        except Exception as e:
            return f"[ERROR] Installation failed: {e}"

    # Construct Command
    cmd = ["kraken", "order"]
    
    if price:
        # Limit Order
        cmd.extend([action, str(price), str(amount), pair])
    else:
        # Market Order
        cmd.extend([action, str(amount), pair])
        
    # Execute
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        
        if result.returncode != 0:
            print(f"[KORA] Kraken Error: {result.stderr}")
            return f"[ERROR] {result.stderr.strip()}"
        else:
            print(f"[KORA] Trade Executed: {result.stdout}")
            return f"[SUCCESS] {result.stdout.strip()}"
            
    except subprocess.TimeoutExpired:
        return "[ERROR] Command timed out."
    except Exception as e:
        return f"[ERROR] {e}"
